version: '3'
services:
  app: &main
    image: ex-data-telemetry
    build: .
    volumes:
      - ./data:/data
    environment:
      - SNOWFLAKE_DB_HOST
      - SNOWFLAKE_DB_USER
      - SNOWFLAKE_DB_PASSWORD
      - SNOWFLAKE_DB_DATABASE
      - SNOWFLAKE_DB_PORT
      - SNOWFLAKE_DB_SCHEMA
      - SNOWFLAKE_DB_WAREHOUSE
      - KBC_PROJECTID
      - KBC_STACKID

  dev:
    <<: *main
    volumes:
      - ./:/code
      - ./data:/data
